import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Grid,
  Box,
} from '@mui/material';
import { Account3, Account3FormData } from '@pharmacy-pos/shared/types/accounting3';
import { Organization } from '@pharmacy-pos/shared/types/organization';
import { AccountFormBasicInfoFields as BasicInfoFields } from './AccountFormBasicInfoFields';
import { AccountFormOrganizationSelector as OrganizationSelector } from './AccountFormOrganizationSelector';
import { AccountFormAccountTypeFields as AccountTypeFields } from './AccountFormAccountTypeFields';
import { AccountFormBalanceAndCurrencyFields as BalanceAndCurrencyFields } from './AccountFormBalanceAndCurrencyFields';
import { AccountFormParentAccountField as ParentAccountField } from './AccountFormParentAccountField';
import { AccountFormStatusAndDescription as FormStatusAndDescription } from './AccountFormStatusAndDescription';

// 表單 Props 介面
interface AccountFormProps {
  open: boolean;
  account?: Account3 | null;
  parentAccount?: Account3 | null; // 父科目資訊
  onClose: () => void;
  onSubmit: (data: Account3FormData) => Promise<void>;
  loading?: boolean;
  organizations?: Organization[];
  selectedOrganizationId?: string | null;
}

// 科目代號前綴對應表
const ACCOUNT_CODE_PREFIXES = {
  asset: '1',
  liability: '2',
  equity: '3',
  revenue: '4',
  expense: '5'
} as const;

/**
 * 科目表單組件
 * 
 * 職責：
 * - 提供新增/編輯科目的表單介面
 * - 表單驗證與資料處理
 * - 支援編輯模式與新增模式
 */
export const AccountForm: React.FC<AccountFormProps> = ({
  open,
  account,
  parentAccount,
  onClose,
  onSubmit,
  loading = false,
  organizations = [],
  selectedOrganizationId
}) => {
  const [formData, setFormData] = useState<Account3FormData>({
    code: '',
    name: '',
    accountType: 'asset',
    type: 'other',
    parentId: '',
    initialBalance: 0,
    currency: 'TWD',
    description: '',
    organizationId: ''
  });

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isActive, setIsActive] = useState(true);
  const [isCodeAutoGenerated, setIsCodeAutoGenerated] = useState(true); // 是否自動生成代號

  // 自動生成科目代號
  const generateAccountCode = (accountType: string, parentCode?: string): string => {
    const prefix = ACCOUNT_CODE_PREFIXES[accountType as keyof typeof ACCOUNT_CODE_PREFIXES];
    
    if (parentCode) {
      // 如果有父科目代號，生成子科目代號
      const nextSubCode = '01'; // 簡化版本，實際應該查詢現有子科目數量
      return `${parentCode}${nextSubCode}`;
    } else {
      // 生成主科目代號
      const nextMainCode = '101'; // 簡化版本，實際應該查詢現有主科目數量
      return `${prefix}${nextMainCode}`;
    }
  };

  // 驗證並修正 type 值
  const validateAccountType = (type: string | undefined): 'cash' | 'bank' | 'credit' | 'investment' | 'other' => {
    const validTypes = ['cash', 'bank', 'credit', 'investment', 'other'];
    return validTypes.includes(type || '') ? (type as 'cash' | 'bank' | 'credit' | 'investment' | 'other') : 'other';
  };

  // 當 account 或 parentAccount 變化時更新表單資料
  useEffect(() => {
    if (account) {
      setFormData({
        code: account.code || '',
        name: account.name || '',
        accountType: account.accountType || (parentAccount?.accountType || 'asset'),
        type: validateAccountType(account.type) || validateAccountType(parentAccount?.type) || 'other',
        parentId: account.parentId || '',
        initialBalance: account.initialBalance || 0,
        currency: account.currency || 'TWD',
        description: account.description || '',
        organizationId: account.organizationId || (parentAccount?.organizationId || selectedOrganizationId || '')
      });
      setIsActive(account.isActive !== undefined ? account.isActive : true);
      setIsCodeAutoGenerated(false); // 編輯模式不自動生成代號
    } else {
      // 重置表單，如果有父科目則繼承其屬性
      const accountType = parentAccount?.accountType || 'asset';
      const autoCode = generateAccountCode(accountType, parentAccount?.code);
      
      setFormData({
        code: autoCode,
        name: '',
        accountType,
        type: validateAccountType(parentAccount?.type),
        parentId: parentAccount?._id || '',
        initialBalance: 0,
        currency: 'TWD',
        description: '',
        organizationId: parentAccount?.organizationId || selectedOrganizationId || ''
      });
      setIsActive(true);
      setIsCodeAutoGenerated(true); // 新增模式自動生成代號
    }
    setErrors({});
  }, [account, parentAccount, open, selectedOrganizationId]);

  // 表單驗證
  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.code.trim()) {
      newErrors.code = '科目代號為必填';
    }

    if (!formData.name.trim()) {
      newErrors.name = '科目名稱為必填';
    }

    if (!formData.accountType) {
      newErrors.accountType = '科目類型為必填';
    }

    if (!formData.type) {
      newErrors.type = '帳戶類型為必填';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // 處理表單提交
  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    try {
      // 處理 parentId：過濾掉虛擬節點 ID
      const processedParentId = formData.parentId &&
        formData.parentId.includes('_') ?
        '' : // 虛擬節點 ID 包含底線，設為空字串
        formData.parentId;

      // 添加 isActive 狀態到提交資料
      const submitData = {
        ...formData,
        parentId: processedParentId || '',
        isActive
      };
      
      console.log('提交科目資料:', submitData);
      console.log('原始 parentId:', formData.parentId, '→ 處理後:', processedParentId);
      
      await onSubmit(submitData);
      onClose();
    } catch (error) {
      console.error('提交表單失敗:', error);
    }
  };

  // 處理輸入變化
  const handleInputChange = (field: keyof Account3FormData, value: any) => {
    setFormData(prev => {
      const newData = { ...prev, [field]: value };
      
      // 如果是科目類型變化且啟用自動生成代號，則更新代號
      if (field === 'accountType' && isCodeAutoGenerated) {
        newData.code = generateAccountCode(value, parentAccount?.code);
      }
      
      return newData;
    });

    // 清除該欄位的錯誤
    if (errors[field]) {
      setErrors(prev => ({
        ...prev,
        [field]: ''
      }));
    }
  };

  // 處理科目代號手動編輯
  const handleCodeChange = (value: string) => {
    setFormData(prev => ({ ...prev, code: value }));
    setIsCodeAutoGenerated(false); // 手動編輯後停用自動生成
    
    // 清除代號欄位的錯誤
    if (errors.code) {
      setErrors(prev => ({ ...prev, code: '' }));
    }
  };

  return (
    <Dialog 
      open={open} 
      onClose={onClose} 
      maxWidth="md" 
      fullWidth
      PaperProps={{
        sx: { minHeight: '500px' }
      }}
    >
      <DialogTitle>
        {account ? '編輯科目' : '新增科目'}
      </DialogTitle>

      <DialogContent>
        <Box sx={{ pt: 1 }}>
          <Grid container spacing={2}>
            {/* 基本資訊 */}
            <BasicInfoFields
              code={formData.code}
              name={formData.name}
              onCodeChange={handleCodeChange}
              onNameChange={(value) => handleInputChange('name', value)}
              errors={errors}
            />

            {/* 機構選擇 */}
            <OrganizationSelector
              organizationId={formData.organizationId || ''}
              organizations={organizations}
              selectedOrganizationId={selectedOrganizationId || null}
              parentAccount={parentAccount || null}
            />

            {/* 科目類型 */}
            <AccountTypeFields
              accountType={formData.accountType}
              type={formData.type}
              onAccountTypeChange={(value) => handleInputChange('accountType', value)}
              onTypeChange={(value) => handleInputChange('type', value)}
              errors={errors}
            />

            {/* 期初餘額與幣別 */}
            <BalanceAndCurrencyFields
              initialBalance={formData.initialBalance}
              currency={formData.currency}
              onInitialBalanceChange={(value) => handleInputChange('initialBalance', value)}
              onCurrencyChange={(value) => handleInputChange('currency', value)}
            />

            {/* 上層科目 */}
            <ParentAccountField
              parentId={formData.parentId || ''}
              parentAccount={parentAccount || null}
              onParentIdChange={(value) => handleInputChange('parentId', value)}
            />

            {/* 狀態開關和描述 */}
            <FormStatusAndDescription
              isActive={isActive}
              description={formData.description || ''}
              onIsActiveChange={setIsActive}
              onDescriptionChange={(value) => handleInputChange('description', value)}
            />
          </Grid>
        </Box>
      </DialogContent>

      <DialogActions>
        <Button onClick={onClose} disabled={loading}>
          取消
        </Button>
        <Button 
          onClick={handleSubmit} 
          variant="contained" 
          disabled={loading}
        >
          {loading ? '處理中...' : (account ? '更新' : '新增')}
        </Button>
      </DialogActions>
    </Dialog>
  );
};

export default AccountForm;