// 現有的 actionTypes.js 內容
export const ActionTypes = {
  // 認證相關
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  
  // 藥品相關
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
  
  // 供應商相關
  FETCH_SUPPLIERS_REQUEST: 'FETCH_SUPPLIERS_REQUEST',
  FETCH_SUPPLIERS_SUCCESS: 'FETCH_SUPPLIERS_SUCCESS',
  FETCH_SUPPLIERS_FAILURE: 'FETCH_SUPPLIERS_FAILURE',
  
  // 會員相關
  FETCH_CUSTOMERS_REQUEST: 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',
  
  // 庫存相關
  FETCH_INVENTORY_REQUEST: 'FETCH_INVENTORY_REQUEST',
  FETCH_INVENTORY_SUCCESS: 'FETCH_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_INVENTORY_FAILURE',
  
  // 銷售相關
  FETCH_SALES_REQUEST: 'FETCH_SALES_REQUEST',
  FETCH_SALES_SUCCESS: 'FETCH_SALES_SUCCESS',
  FETCH_SALES_FAILURE: 'FETCH_SALES_FAILURE',
  
  // 儀表板相關
  FETCH_DASHBOARD_DATA_REQUEST: 'FETCH_DASHBOARD_DATA_REQUEST',
  FETCH_DASHBOARD_DATA_SUCCESS: 'FETCH_DASHBOARD_DATA_SUCCESS',
  FETCH_DASHBOARD_DATA_FAILURE: 'FETCH_DASHBOARD_DATA_FAILURE',
  
  // 報表相關
  FETCH_REPORTS_DATA_REQUEST: 'FETCH_REPORTS_DATA_REQUEST',
  FETCH_REPORTS_DATA_SUCCESS: 'FETCH_REPORTS_DATA_SUCCESS',
  FETCH_REPORTS_DATA_FAILURE: 'FETCH_REPORTS_DATA_FAILURE',
  
  // 進貨單相關
  FETCH_PURCHASE_ORDERS_REQUEST: 'FETCH_PURCHASE_ORDERS_REQUEST',
  FETCH_PURCHASE_ORDERS_SUCCESS: 'FETCH_PURCHASE_ORDERS_SUCCESS',
  FETCH_PURCHASE_ORDERS_FAILURE: 'FETCH_PURCHASE_ORDERS_FAILURE',
  FETCH_PURCHASE_ORDER_REQUEST: 'FETCH_PURCHASE_ORDER_REQUEST',
  FETCH_PURCHASE_ORDER_SUCCESS: 'FETCH_PURCHASE_ORDER_SUCCESS',
  FETCH_PURCHASE_ORDER_FAILURE: 'FETCH_PURCHASE_ORDER_FAILURE',
  ADD_PURCHASE_ORDER_REQUEST: 'ADD_PURCHASE_ORDER_REQUEST',
  ADD_PURCHASE_ORDER_SUCCESS: 'ADD_PURCHASE_ORDER_SUCCESS',
  ADD_PURCHASE_ORDER_FAILURE: 'ADD_PURCHASE_ORDER_FAILURE',
  UPDATE_PURCHASE_ORDER_REQUEST: 'UPDATE_PURCHASE_ORDER_REQUEST',
  UPDATE_PURCHASE_ORDER_SUCCESS: 'UPDATE_PURCHASE_ORDER_SUCCESS',
  UPDATE_PURCHASE_ORDER_FAILURE: 'UPDATE_PURCHASE_ORDER_FAILURE',
  DELETE_PURCHASE_ORDER_REQUEST: 'DELETE_PURCHASE_ORDER_REQUEST',
  DELETE_PURCHASE_ORDER_SUCCESS: 'DELETE_PURCHASE_ORDER_SUCCESS',
  DELETE_PURCHASE_ORDER_FAILURE: 'DELETE_PURCHASE_ORDER_FAILURE',
  SEARCH_PURCHASE_ORDERS_REQUEST: 'SEARCH_PURCHASE_ORDERS_REQUEST',
  SEARCH_PURCHASE_ORDERS_SUCCESS: 'SEARCH_PURCHASE_ORDERS_SUCCESS',
  SEARCH_PURCHASE_ORDERS_FAILURE: 'SEARCH_PURCHASE_ORDERS_FAILURE',
  
  // 出貨單相關
  FETCH_SHIPPING_ORDERS_REQUEST: 'FETCH_SHIPPING_ORDERS_REQUEST',
  FETCH_SHIPPING_ORDERS_SUCCESS: 'FETCH_SHIPPING_ORDERS_SUCCESS',
  FETCH_SHIPPING_ORDERS_FAILURE: 'FETCH_SHIPPING_ORDERS_FAILURE',
  FETCH_SHIPPING_ORDER_REQUEST: 'FETCH_SHIPPING_ORDER_REQUEST',
  FETCH_SHIPPING_ORDER_SUCCESS: 'FETCH_SHIPPING_ORDER_SUCCESS',
  FETCH_SHIPPING_ORDER_FAILURE: 'FETCH_SHIPPING_ORDER_FAILURE',
  ADD_SHIPPING_ORDER_REQUEST: 'ADD_SHIPPING_ORDER_REQUEST',
  ADD_SHIPPING_ORDER_SUCCESS: 'ADD_SHIPPING_ORDER_SUCCESS',
  ADD_SHIPPING_ORDER_FAILURE: 'ADD_SHIPPING_ORDER_FAILURE',
  UPDATE_SHIPPING_ORDER_REQUEST: 'UPDATE_SHIPPING_ORDER_REQUEST',
  UPDATE_SHIPPING_ORDER_SUCCESS: 'UPDATE_SHIPPING_ORDER_SUCCESS',
  UPDATE_SHIPPING_ORDER_FAILURE: 'UPDATE_SHIPPING_ORDER_FAILURE',
  DELETE_SHIPPING_ORDER_REQUEST: 'DELETE_SHIPPING_ORDER_REQUEST',
  DELETE_SHIPPING_ORDER_SUCCESS: 'DELETE_SHIPPING_ORDER_SUCCESS',
  DELETE_SHIPPING_ORDER_FAILURE: 'DELETE_SHIPPING_ORDER_FAILURE',
  SEARCH_SHIPPING_ORDERS_REQUEST: 'SEARCH_SHIPPING_ORDERS_REQUEST',
  SEARCH_SHIPPING_ORDERS_SUCCESS: 'SEARCH_SHIPPING_ORDERS_SUCCESS',
  SEARCH_SHIPPING_ORDERS_FAILURE: 'SEARCH_SHIPPING_ORDERS_FAILURE'
};
