// 動作類型常量
export const ActionTypes = {
  // 認證相關
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  
  // 藥品相關
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
  
  // 供應商相關
  FETCH_SUPPLIERS_REQUEST: 'FETCH_SUPPLIERS_REQUEST',
  FETCH_SUPPLIERS_SUCCESS: 'FETCH_SUPPLIERS_SUCCESS',
  FETCH_SUPPLIERS_FAILURE: 'FETCH_SUPPLIERS_FAILURE',
  ADD_SUPPLIER_REQUEST: 'ADD_SUPPLIER_REQUEST',
  ADD_SUPPLIER_SUCCESS: 'ADD_SUPPLIER_SUCCESS',
  ADD_SUPPLIER_FAILURE: 'ADD_SUPPLIER_FAILURE',
  UPDATE_SUPPLIER_REQUEST: 'UPDATE_SUPPLIER_REQUEST',
  UPDATE_SUPPLIER_SUCCESS: 'UPDATE_SUPPLIER_SUCCESS',
  UPDATE_SUPPLIER_FAILURE: 'UPDATE_SUPPLIER_FAILURE',
  DELETE_SUPPLIER_REQUEST: 'DELETE_SUPPLIER_REQUEST',
  DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
  DELETE_SUPPLIER_FAILURE: 'DELETE_SUPPLIER_FAILURE',
  
  // 會員相關
  FETCH_CUSTOMERS_REQUEST: 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',
  ADD_CUSTOMER_REQUEST: 'ADD_CUSTOMER_REQUEST',
  ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
  ADD_CUSTOMER_FAILURE: 'ADD_CUSTOMER_FAILURE',
  UPDATE_CUSTOMER_REQUEST: 'UPDATE_CUSTOMER_REQUEST',
  UPDATE_CUSTOMER_SUCCESS: 'UPDATE_CUSTOMER_SUCCESS',
  UPDATE_CUSTOMER_FAILURE: 'UPDATE_CUSTOMER_FAILURE',
  DELETE_CUSTOMER_REQUEST: 'DELETE_CUSTOMER_REQUEST',
  DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
  DELETE_CUSTOMER_FAILURE: 'DELETE_CUSTOMER_FAILURE',
  
  // 庫存相關
  FETCH_INVENTORY_REQUEST: 'FETCH_INVENTORY_REQUEST',
  FETCH_INVENTORY_SUCCESS: 'FETCH_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_INVENTORY_FAILURE',
  ADD_INVENTORY_REQUEST: 'ADD_INVENTORY_REQUEST',
  ADD_INVENTORY_SUCCESS: 'ADD_INVENTORY_SUCCESS',
  ADD_INVENTORY_FAILURE: 'ADD_INVENTORY_FAILURE',
  UPDATE_INVENTORY_REQUEST: 'UPDATE_INVENTORY_REQUEST',
  UPDATE_INVENTORY_SUCCESS: 'UPDATE_INVENTORY_SUCCESS',
  UPDATE_INVENTORY_FAILURE: 'UPDATE_INVENTORY_FAILURE',
  DELETE_INVENTORY_REQUEST: 'DELETE_INVENTORY_REQUEST',
  DELETE_INVENTORY_SUCCESS: 'DELETE_INVENTORY_SUCCESS',
  DELETE_INVENTORY_FAILURE: 'DELETE_INVENTORY_FAILURE',
  
  // 銷售相關
  FETCH_SALES_REQUEST: 'FETCH_SALES_REQUEST',
  FETCH_SALES_SUCCESS: 'FETCH_SALES_SUCCESS',
  FETCH_SALES_FAILURE: 'FETCH_SALES_FAILURE',
  ADD_SALE_REQUEST: 'ADD_SALE_REQUEST',
  ADD_SALE_SUCCESS: 'ADD_SALE_SUCCESS',
  ADD_SALE_FAILURE: 'ADD_SALE_FAILURE',
  UPDATE_SALE_REQUEST: 'UPDATE_SALE_REQUEST',
  UPDATE_SALE_SUCCESS: 'UPDATE_SALE_SUCCESS',
  UPDATE_SALE_FAILURE: 'UPDATE_SALE_FAILURE',
  DELETE_SALE_REQUEST: 'DELETE_SALE_REQUEST',
  DELETE_SALE_SUCCESS: 'DELETE_SALE_SUCCESS',
  DELETE_SALE_FAILURE: 'DELETE_SALE_FAILURE',
  
  // 儀表板相關
  FETCH_DASHBOARD_DATA_REQUEST: 'FETCH_DASHBOARD_DATA_REQUEST',
  FETCH_DASHBOARD_DATA_SUCCESS: 'FETCH_DASHBOARD_DATA_SUCCESS',
  FETCH_DASHBOARD_DATA_FAILURE: 'FETCH_DASHBOARD_DATA_FAILURE',
  
  // 報表相關
  FETCH_REPORTS_DATA_REQUEST: 'FETCH_REPORTS_DATA_REQUEST',
  FETCH_REPORTS_DATA_SUCCESS: 'FETCH_REPORTS_DATA_SUCCESS',
  FETCH_REPORTS_DATA_FAILURE: 'FETCH_REPORTS_DATA_FAILURE',
};
