/**
 * Redux Action Types
 * 使用工廠函數生成標準的 CRUD 動作類型，減少重複程式碼
 */

/**
 * Redux Action Types
 * 重構後的動作類型定義，減少重複程式碼並提高可維護性
 */

/**
 * 認證相關動作類型
 */
const AuthActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
} as const;

/**
 * 基本實體動作類型
 */
const ProductActionTypes = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCTS_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  ADD_PRODUCTS_REQUEST: 'ADD_PRODUCTS_REQUEST',
  ADD_PRODUCTS_SUCCESS: 'ADD_PRODUCTS_SUCCESS',
  ADD_PRODUCTS_FAILURE: 'ADD_PRODUCTS_FAILURE',
  UPDATE_PRODUCTS_REQUEST: 'UPDATE_PRODUCTS_REQUEST',
  UPDATE_PRODUCTS_SUCCESS: 'UPDATE_PRODUCTS_SUCCESS',
  UPDATE_PRODUCTS_FAILURE: 'UPDATE_PRODUCTS_FAILURE',
  DELETE_PRODUCTS_REQUEST: 'DELETE_PRODUCTS_REQUEST',
  DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
  DELETE_PRODUCTS_FAILURE: 'DELETE_PRODUCTS_FAILURE',
  
  // 單數形式 (向後相容)
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
} as const;
const SupplierActionTypes = {
  FETCH_SUPPLIERS_REQUEST: 'FETCH_SUPPLIERS_REQUEST',
  FETCH_SUPPLIERS_SUCCESS: 'FETCH_SUPPLIERS_SUCCESS',
  FETCH_SUPPLIERS_FAILURE: 'FETCH_SUPPLIERS_FAILURE',
} as const;

const CustomerActionTypes = {
  FETCH_CUSTOMERS_REQUEST: 'FETCH_CUSTOMERS_REQUEST',
  FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',
  FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',
} as const;

const InventoryActionTypes = {
  FETCH_INVENTORY_REQUEST: 'FETCH_INVENTORY_REQUEST',
  FETCH_INVENTORY_SUCCESS: 'FETCH_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_INVENTORY_FAILURE',
} as const;

const SalesActionTypes = {
  FETCH_SALES_REQUEST: 'FETCH_SALES_REQUEST',
  FETCH_SALES_SUCCESS: 'FETCH_SALES_SUCCESS',
  FETCH_SALES_FAILURE: 'FETCH_SALES_FAILURE',
} as const;

/**
 * 複雜實體動作類型（包含單一實體操作）
 */
const PurchaseOrderActionTypes = {
  // 複數形式 (從 createCrudActionTypes 生成)
  FETCH_PURCHASE_ORDERS_REQUEST: 'FETCH_PURCHASE_ORDERS_REQUEST',
  FETCH_PURCHASE_ORDERS_SUCCESS: 'FETCH_PURCHASE_ORDERS_SUCCESS',
  FETCH_PURCHASE_ORDERS_FAILURE: 'FETCH_PURCHASE_ORDERS_FAILURE',
  ADD_PURCHASE_ORDERS_REQUEST: 'ADD_PURCHASE_ORDERS_REQUEST',
  ADD_PURCHASE_ORDERS_SUCCESS: 'ADD_PURCHASE_ORDERS_SUCCESS',
  ADD_PURCHASE_ORDERS_FAILURE: 'ADD_PURCHASE_ORDERS_FAILURE',
  UPDATE_PURCHASE_ORDERS_REQUEST: 'UPDATE_PURCHASE_ORDERS_REQUEST',
  UPDATE_PURCHASE_ORDERS_SUCCESS: 'UPDATE_PURCHASE_ORDERS_SUCCESS',
  UPDATE_PURCHASE_ORDERS_FAILURE: 'UPDATE_PURCHASE_ORDERS_FAILURE',
  DELETE_PURCHASE_ORDERS_REQUEST: 'DELETE_PURCHASE_ORDERS_REQUEST',
  DELETE_PURCHASE_ORDERS_SUCCESS: 'DELETE_PURCHASE_ORDERS_SUCCESS',
  DELETE_PURCHASE_ORDERS_FAILURE: 'DELETE_PURCHASE_ORDERS_FAILURE',
  
  // 單數形式 (向後相容)
  FETCH_PURCHASE_ORDER_REQUEST: 'FETCH_PURCHASE_ORDER_REQUEST',
  FETCH_PURCHASE_ORDER_SUCCESS: 'FETCH_PURCHASE_ORDER_SUCCESS',
  FETCH_PURCHASE_ORDER_FAILURE: 'FETCH_PURCHASE_ORDER_FAILURE',
  ADD_PURCHASE_ORDER_REQUEST: 'ADD_PURCHASE_ORDER_REQUEST',
  ADD_PURCHASE_ORDER_SUCCESS: 'ADD_PURCHASE_ORDER_SUCCESS',
  ADD_PURCHASE_ORDER_FAILURE: 'ADD_PURCHASE_ORDER_FAILURE',
  UPDATE_PURCHASE_ORDER_REQUEST: 'UPDATE_PURCHASE_ORDER_REQUEST',
  UPDATE_PURCHASE_ORDER_SUCCESS: 'UPDATE_PURCHASE_ORDER_SUCCESS',
  UPDATE_PURCHASE_ORDER_FAILURE: 'UPDATE_PURCHASE_ORDER_FAILURE',
  DELETE_PURCHASE_ORDER_REQUEST: 'DELETE_PURCHASE_ORDER_REQUEST',
  DELETE_PURCHASE_ORDER_SUCCESS: 'DELETE_PURCHASE_ORDER_SUCCESS',
  DELETE_PURCHASE_ORDER_FAILURE: 'DELETE_PURCHASE_ORDER_FAILURE',
  
  // 搜尋相關
  SEARCH_PURCHASE_ORDERS_REQUEST: 'SEARCH_PURCHASE_ORDERS_REQUEST',
  SEARCH_PURCHASE_ORDERS_SUCCESS: 'SEARCH_PURCHASE_ORDERS_SUCCESS',
  SEARCH_PURCHASE_ORDERS_FAILURE: 'SEARCH_PURCHASE_ORDERS_FAILURE',
} as const;

const ShippingOrderActionTypes = {
  // 複數形式 (從 createCrudActionTypes 生成)
  FETCH_SHIPPING_ORDERS_REQUEST: 'FETCH_SHIPPING_ORDERS_REQUEST',
  FETCH_SHIPPING_ORDERS_SUCCESS: 'FETCH_SHIPPING_ORDERS_SUCCESS',
  FETCH_SHIPPING_ORDERS_FAILURE: 'FETCH_SHIPPING_ORDERS_FAILURE',
  ADD_SHIPPING_ORDERS_REQUEST: 'ADD_SHIPPING_ORDERS_REQUEST',
  ADD_SHIPPING_ORDERS_SUCCESS: 'ADD_SHIPPING_ORDERS_SUCCESS',
  ADD_SHIPPING_ORDERS_FAILURE: 'ADD_SHIPPING_ORDERS_FAILURE',
  UPDATE_SHIPPING_ORDERS_REQUEST: 'UPDATE_SHIPPING_ORDERS_REQUEST',
  UPDATE_SHIPPING_ORDERS_SUCCESS: 'UPDATE_SHIPPING_ORDERS_SUCCESS',
  UPDATE_SHIPPING_ORDERS_FAILURE: 'UPDATE_SHIPPING_ORDERS_FAILURE',
  DELETE_SHIPPING_ORDERS_REQUEST: 'DELETE_SHIPPING_ORDERS_REQUEST',
  DELETE_SHIPPING_ORDERS_SUCCESS: 'DELETE_SHIPPING_ORDERS_SUCCESS',
  DELETE_SHIPPING_ORDERS_FAILURE: 'DELETE_SHIPPING_ORDERS_FAILURE',
  
  // 單數形式 (向後相容)
  FETCH_SHIPPING_ORDER_REQUEST: 'FETCH_SHIPPING_ORDER_REQUEST',
  FETCH_SHIPPING_ORDER_SUCCESS: 'FETCH_SHIPPING_ORDER_SUCCESS',
  FETCH_SHIPPING_ORDER_FAILURE: 'FETCH_SHIPPING_ORDER_FAILURE',
  ADD_SHIPPING_ORDER_REQUEST: 'ADD_SHIPPING_ORDER_REQUEST',
  ADD_SHIPPING_ORDER_SUCCESS: 'ADD_SHIPPING_ORDER_SUCCESS',
  ADD_SHIPPING_ORDER_FAILURE: 'ADD_SHIPPING_ORDER_FAILURE',
  UPDATE_SHIPPING_ORDER_REQUEST: 'UPDATE_SHIPPING_ORDER_REQUEST',
  UPDATE_SHIPPING_ORDER_SUCCESS: 'UPDATE_SHIPPING_ORDER_SUCCESS',
  UPDATE_SHIPPING_ORDER_FAILURE: 'UPDATE_SHIPPING_ORDER_FAILURE',
  DELETE_SHIPPING_ORDER_REQUEST: 'DELETE_SHIPPING_ORDER_REQUEST',
  DELETE_SHIPPING_ORDER_SUCCESS: 'DELETE_SHIPPING_ORDER_SUCCESS',
  DELETE_SHIPPING_ORDER_FAILURE: 'DELETE_SHIPPING_ORDER_FAILURE',
  
  // 搜尋相關
  SEARCH_SHIPPING_ORDERS_REQUEST: 'SEARCH_SHIPPING_ORDERS_REQUEST',
  SEARCH_SHIPPING_ORDERS_SUCCESS: 'SEARCH_SHIPPING_ORDERS_SUCCESS',
  SEARCH_SHIPPING_ORDERS_FAILURE: 'SEARCH_SHIPPING_ORDERS_FAILURE',
} as const;

/**
 * 儀表板和報表動作類型
 */
const DashboardActionTypes = {
  FETCH_DASHBOARD_DATA_REQUEST: 'FETCH_DASHBOARD_DATA_REQUEST',
  FETCH_DASHBOARD_DATA_SUCCESS: 'FETCH_DASHBOARD_DATA_SUCCESS',
  FETCH_DASHBOARD_DATA_FAILURE: 'FETCH_DASHBOARD_DATA_FAILURE',
} as const;

const ReportsActionTypes = {
  FETCH_REPORTS_DATA_REQUEST: 'FETCH_REPORTS_DATA_REQUEST',
  FETCH_REPORTS_DATA_SUCCESS: 'FETCH_REPORTS_DATA_SUCCESS',
  FETCH_REPORTS_DATA_FAILURE: 'FETCH_REPORTS_DATA_FAILURE',
} as const;

/**
 * 合併所有動作類型
 */
export const ActionTypes = {
  ...AuthActionTypes,
  ...ProductActionTypes,
  ...SupplierActionTypes,
  ...CustomerActionTypes,
  ...InventoryActionTypes,
  ...SalesActionTypes,
  ...DashboardActionTypes,
  ...ReportsActionTypes,
  ...PurchaseOrderActionTypes,
  ...ShippingOrderActionTypes,
} as const;

/**
 * ActionTypes 的類型，用於類型檢查
 */
export type ActionType = typeof ActionTypes[keyof typeof ActionTypes];

/**
 * 按模組分組的動作類型，便於使用
 */
export const ActionTypeGroups = {
  Auth: AuthActionTypes,
  Products: ProductActionTypes,
  Suppliers: SupplierActionTypes,
  Customers: CustomerActionTypes,
  Inventory: InventoryActionTypes,
  Sales: SalesActionTypes,
  Dashboard: DashboardActionTypes,
  Reports: ReportsActionTypes,
  PurchaseOrders: PurchaseOrderActionTypes,
  ShippingOrders: ShippingOrderActionTypes,
} as const;