name: Release Tooling

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "shared/**"
      - "openapi/**"
      - "backend/**"
      - "frontend/**"
      - "scripts/release/**"
      - "docs/release-playbook.md"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  actions: write
  checks: write
  id-token: write

jobs:
  release-tools:
    name: Generate release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run release automation
        run: pnpm run release:auto -- --skip-tests --skip-type-check --skip-collect --skip-verify --output artifacts/release

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: artifacts/release
          if-no-files-found: error

      - name: Post summary
        if: always()
        run: |
          SUMMARY=<<'EOF'
          ### Release Tooling Summary
          - Schema diff: artifacts/release/schema-diff.md\n          - Version report: artifacts/release/version-bump.json\n          - coverage summary: artifacts/release/auto-bundle/coverage-summary.json\n          - LTS matrix: artifacts/release/lts-matrix.json
          EOF
          echo "$SUMMARY" >> "$GITHUB_STEP_SUMMARY"





